name: skript-nbs
main: com.github.hapily04.skriptnbs.SkriptNbs
version: @version@
api-version: 1.13
depend: [Skript]
authors: [hapily]
website: https://github.com/skript-minestom/skript-nbs
description: Play Note Block Studio (.nbs) songs via NoteBlockAPI on Skript-Minestom.
